spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/computer_store
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 自定义配置参数
#Srping读取配置文件中数据: @Value("${user.address.max-count}")
user:
  address:
    max-count: 20